-- ============================================
-- File Formats
-- ============================================

USE DATABASE STOCK_ANALYTICS;
USE SCHEMA RAW;

CREATE OR REPLACE FILE FORMAT FF_STOCK_COMPANIES
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL');

CREATE OR REPLACE FILE FORMAT FF_STOCK_EXCHANGES
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL');

CREATE OR REPLACE FILE FORMAT FF_STOCK_PRICES
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL');

CREATE OR REPLACE FILE FORMAT FF_STOCK_CORPORATE_ACTIONS
    TYPE = CSV
    SKIP_HEADER = 1
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL');