-- ============================================
-- Stock Analytics Platform
-- RAW Layer Table Definitions
-- ============================================

USE DATABASE STOCK_ANALYTICS;
USE SCHEMA RAW;

-- ============================================
-- RAW COMPANIES
-- ============================================

CREATE OR REPLACE TABLE RAW_COMPANIES (
    COMPANY_ID VARCHAR,
    TICKER VARCHAR,
    COMPANY_NAME VARCHAR,
    SECTOR VARCHAR,
    INDUSTRY VARCHAR,
    MARKET_CAP_BAND VARCHAR,
    COUNTRY VARCHAR,
    PRIMARY_EXCHANGE_ID VARCHAR,
    STATUS VARCHAR,
    LISTED_SINCE VARCHAR,
    UPDATED_AT VARCHAR,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR,
    FILE_ROW_NUMBER NUMBER
);

-- ============================================
-- RAW EXCHANGES
-- ============================================

CREATE OR REPLACE TABLE RAW_EXCHANGES (
    EXCHANGE_ID VARCHAR,
    EXCHANGE_CODE VARCHAR,
    COUNTRY VARCHAR,
    CURRENCY VARCHAR,
    TIMEZONE VARCHAR,
    MARKET_TYPE VARCHAR,
    STATUS VARCHAR,
    ESTABLISHED_DATE VARCHAR,
    UPDATED_AT VARCHAR,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR,
    FILE_ROW_NUMBER NUMBER
);

-- ============================================
-- RAW DAILY PRICES
-- ============================================

CREATE OR REPLACE TABLE RAW_PRICES_DAILY (
    PRICE_ID VARCHAR,
    TRADE_DATE VARCHAR,
    COMPANY_ID VARCHAR,
    EXCHANGE_ID VARCHAR,
    OPEN VARCHAR,
    HIGH VARCHAR,
    LOW VARCHAR,
    CLOSE VARCHAR,
    ADJ_CLOSE VARCHAR,
    VOLUME VARCHAR,
    VWAP VARCHAR,
    UPDATED_AT VARCHAR,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR,
    FILE_ROW_NUMBER NUMBER
);

-- ============================================
-- RAW CORPORATE ACTIONS
-- ============================================

CREATE OR REPLACE TABLE RAW_CORPORATE_ACTIONS (
    ACTION_ID VARCHAR,
    COMPANY_ID VARCHAR,
    TICKER VARCHAR,
    ACTION_TYPE VARCHAR,
    EX_DATE VARCHAR,
    RECORD_DATE VARCHAR,
    PAY_DATE VARCHAR,
    ACTION_VALUE VARCHAR,
    RATIO VARCHAR,
    CURRENCY VARCHAR,
    STATUS VARCHAR,
    UPDATED_AT VARCHAR,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    FILE_NAME VARCHAR,
    FILE_ROW_NUMBER NUMBER
);