-- ============================================
-- Snowpipe Definitions
-- ============================================

USE DATABASE STOCK_ANALYTICS;
USE SCHEMA RAW;

CREATE OR REPLACE PIPE STOCK_COMPANIES_PIPE
AS
COPY INTO STOCK_ANALYTICS.RAW.RAW_COMPANIES
FROM @STOCK_ANALYTICS.RAW.S3_STOCK_STAGE/companies/
FILE_FORMAT = (
    FORMAT_NAME = 'STOCK_ANALYTICS.RAW.FF_STOCK_COMPANIES'
)
ON_ERROR = 'CONTINUE';


CREATE OR REPLACE PIPE STOCK_EXCHANGES_PIPE
AS
COPY INTO STOCK_ANALYTICS.RAW.RAW_EXCHANGES
FROM @STOCK_ANALYTICS.RAW.S3_STOCK_STAGE/exchanges/
FILE_FORMAT = (
    FORMAT_NAME = 'STOCK_ANALYTICS.RAW.FF_STOCK_EXCHANGES'
)
ON_ERROR = 'CONTINUE';


CREATE OR REPLACE PIPE STOCK_PRICES_PIPE
AS
COPY INTO STOCK_ANALYTICS.RAW.RAW_PRICES_DAILY
FROM @STOCK_ANALYTICS.RAW.S3_STOCK_STAGE/prices/
FILE_FORMAT = (
    FORMAT_NAME = 'STOCK_ANALYTICS.RAW.FF_STOCK_PRICES'
)
ON_ERROR = 'CONTINUE';


CREATE OR REPLACE PIPE STOCK_CORPORATE_ACTIONS_PIPE
AS
COPY INTO STOCK_ANALYTICS.RAW.RAW_CORPORATE_ACTIONS
FROM @STOCK_ANALYTICS.RAW.S3_STOCK_STAGE/corporate_actions/
FILE_FORMAT = (
    FORMAT_NAME = 'STOCK_ANALYTICS.RAW.FF_STOCK_CORPORATE_ACTIONS'
)
ON_ERROR = 'CONTINUE';