-- ============================================
-- Pipeline Validation
-- ============================================

SELECT
    'COMPANIES' AS SOURCE,
    COUNT(*) AS ROW_COUNT
FROM STOCK_ANALYTICS.RAW.RAW_COMPANIES

UNION ALL

SELECT
    'EXCHANGES',
    COUNT(*)
FROM STOCK_ANALYTICS.RAW.RAW_EXCHANGES

UNION ALL

SELECT
    'PRICES',
    COUNT(*)
FROM STOCK_ANALYTICS.RAW.RAW_PRICES_DAILY

UNION ALL

SELECT
    'CORPORATE_ACTIONS',
    COUNT(*)
FROM STOCK_ANALYTICS.RAW.RAW_CORPORATE_ACTIONS;

-- Check RAW data

SELECT *
FROM STOCK_ANALYTICS.RAW.RAW_COMPANIES
LIMIT 5;

SELECT *
FROM STOCK_ANALYTICS.RAW.RAW_EXCHANGES
LIMIT 5;

SELECT *
FROM STOCK_ANALYTICS.RAW.RAW_PRICES_DAILY
LIMIT 5;

SELECT *
FROM STOCK_ANALYTICS.RAW.RAW_CORPORATE_ACTIONS
LIMIT 5;

-- ============================================
-- Data Warehouse Validation
-- ============================================

SELECT
    'DIM_DATE' AS OBJECT_NAME,
    COUNT(*) AS ROW_COUNT
FROM STOCK_ANALYTICS.DW.DIM_DATE

UNION ALL

SELECT
    'DIM_EXCHANGE',
    COUNT(*)
FROM STOCK_ANALYTICS.DW.DIM_EXCHANGE

UNION ALL

SELECT
    'DIM_COMPANY',
    COUNT(*)
FROM STOCK_ANALYTICS.DW.DIM_COMPANY

UNION ALL

SELECT
    'FACT_DAILY_PRICE',
    COUNT(*)
FROM STOCK_ANALYTICS.DW.FACT_DAILY_PRICE

UNION ALL

SELECT
    'FACT_CORPORATE_ACTIONS',
    COUNT(*)
FROM STOCK_ANALYTICS.DW.FACT_CORPORATE_ACTIONS;

SELECT
    'STOCK_DAILY_ANALYTICS' AS OBJECT_NAME,
    COUNT(*) AS ROW_COUNT
FROM STOCK_ANALYTICS.SEM.STOCK_DAILY_ANALYTICS

UNION ALL

SELECT
    'COMPANY_PERFORMANCE',
    COUNT(*)
FROM STOCK_ANALYTICS.SEM.COMPANY_PERFORMANCE

UNION ALL

SELECT
    'MARKET_MOVERS',
    COUNT(*)
FROM STOCK_ANALYTICS.SEM.MARKET_MOVERS

UNION ALL

SELECT
    'SECTOR_EXCHANGE_SUMMARY',
    COUNT(*)
FROM STOCK_ANALYTICS.SEM.SECTOR_EXCHANGE_SUMMARY;